### ISSUE TITLE
Invisible text for XIVA modding on certain raids

### ISSUE THREAD

**Issue by wacomintuos** [Soreepeong/XivAlexander#332] opened 2022-01-25 14:01 UTC
There is currently an issue when using J Client and using XIVAlexander modding to display English text in certain raids.

You can do this by using FFXIV J Client and enabling Modding -> Force Display Language (x64) -> English.

On P4S, the text "Role Call", "Nearsight" and "Farsight" is invisible using XIVA modding. The cast bar will show and progress, but there is no text when the boss casts these mechanics. So it's just a cast bar with no text.

**Comment by CharonM72** [comment] 2022-01-25 23:49
This appears to be a duplicate of #305

**Comment by Soreepeong** [comment] 2022-02-03 23:04
This is expected at the moment, as P4S related stuff are hidden until you actually enter the map, and XivAlexander cannot deal with that at the moment. Closing as duplicate of that.

**Closed by Soreepeong** 2022-02-03 23:04 UTC
