### ISSUE TITLE
had this crash twice today, once in cutscene and another in world

### ISSUE THREAD

**Issue by Dedoooo** [Soreepeong/XivAlexander#234] opened 2021-12-10 22:11 UTC
https://prnt.sc/22ntijk is it caused by xivalexander itself or ff14?

**Comment by clemmyn23** [comment] 2021-12-11 06:12
Just got the same crash. 

Log here (doesn't look that useful?) 
[XivAlexander_20211211_171054_137.log](https://github.com/Soreepeong/XivAlexander/files/7696543/XivAlexander_20211211_171054_137.log)

**Comment by clemmyn23** [comment] 2021-12-11 06:14
Hmmm seems to be a duplicate of https://github.com/Soreepeong/XivAlexander/issues/230#issuecomment-990727621
See comments inside for explanation

**Comment by Dedoooo** [comment] 2021-12-11 09:58
i believe both times the crash occured as i was tabbing back in the game.

**Comment by Soreepeong** [comment] 2021-12-13 08:08
Just try again. I don't know why, but it occasionally would show that error message: `Unable to launch application. Launch using the ffxivboot.exe file.(0)`. Using [https://github.com/goatcorp/FFXIVQuickLauncher](FFXIVQuickLauncher) might prevent this from happening.

**Closed** 2021-12-22 06:09 UTC
