### ISSUE TITLE
2+ charges abilities bugging

### ISSUE THREAD

**Issue by yuri2203** [Soreepeong/XivAlexander#144] opened 2021-09-06 02:16 UTC
hello!

i dont know if someone have seen that, but sometimes my Ricochet/Gauss Round gets a cooldown as if there were no charge, but when the timer ends, i have all charges available.

example: the timer is "2 seconds" but i have at least more than 1 charge available.

![image](https://user-images.githubusercontent.com/26317471/132151148-96936204-bcd2-4aeb-85c6-16e449e81516.png)

this started to happen when i got the alexander running.

any thoughts?

**Comment by Soreepeong** [comment] 2021-09-10 07:37
I have never saw this happening from my side, nor know how to play machinist enough to see what's going on. Can you save logs from XivAlex and post it here?

**Comment by MnFeN** [comment] 2021-09-11 16:32
I think it is because you have just reached lv. 74 and learnt the feature which could charge these abilities to 3 😂﻿

**Comment by yuri2203** [comment] 2021-09-11 19:28
I'm trying all these days to reproduce this bug, but it's a bit inconsistent. As soon as I get it again, I'll send the logs!

And no, I'm MCH main since last year, so I'm lv 80 a long time xD

**Comment by Heinzen** [comment] 2021-09-26 16:16
Never had it happen, also main MCH

**Comment by Soreepeong** [comment] 2021-09-29 04:22
Maybe was a one-off thing that happens when your max charge goes up for an action? Closing for now; reopen if you figure out how to reproduce it reliably.

**Closed by Soreepeong** 2021-09-29 04:22 UTC
